== Asynchronous Update Staleness <issue-asynchronous-update-staleness>

Distributed training can overlap communication, computation, and model dissemination instead of
waiting for every participant at a synchronization barrier. This increases hardware utilization and
lets faster or better-connected workers contribute sooner, but the trainer may then consume work
computed from an earlier model state. A delayed gradient or parameter displacement can be combined
with newer updates, and an RL rollout can have been generated by an older behavior policy
@kaleEagerUpdatesOverlapped2025 @teamINTELLECT2ReasoningModel2025.

The effect depends on what becomes stale. For ordinary distributed optimization, delayed updates can
weaken the agreement between workers and cause the aggregate to represent a model state that no
longer exists. For RL, stale rollouts create an off-policy mismatch: the current policy is optimized
using responses sampled under a past policy. In both cases, longer communication, queueing, or
checkpoint-dissemination delays generally increase the mismatch, although the resulting quality loss
depends on the optimizer, task, and magnitude of the intervening changes.

Methods can bound the allowed version lag, discard overly old contributions, correct an aggregate
with locally current information, or constrain update size through clipping and related stability
measures. These measures mitigate rather than eliminate the central trade-off: reducing waits can
increase useful parallelism, while stronger synchronization produces fresher data at the cost of
idle time and sensitivity to slow workers. The choice should therefore report both system benefits
and the tolerated source and degree of staleness.
