== Reinforcement Learning <background-reinforcement-learning>

Reinforcement learning (RL) optimizes a decision-making policy through interaction and feedback. At
time $t$, an agent observes a state $s_t$, selects an action $a_t$, receives a reward $r_t$, and
reaches a subsequent state $s_(t + 1)$. Its objective is to maximize expected discounted return,

$
  G_t = sum_(k = 0)^infinity gamma^k r_(t + k),
$

where $gamma in [0, 1]$ discounts later rewards. A policy $pi(a | s)$ specifies the probability of
selecting an action in a state. A complete sequence of interactions is a trajectory (also called a
rollout or episode).

=== Value functions and method families

The state-value function $V^pi(s) = E_pi[G_t | s_t = s]$ estimates the expected return from a state,
while the action-value function $Q^pi(s, a) = E_pi[G_t | s_t = s, a_t = a]$ estimates the return
after a particular action. The advantage function compares an action with the usual outcome from
that state:

$
  A^pi(s, a) = Q^pi(s, a) - V^pi(s).
$

Value-based methods estimate action values and choose high-valued actions; Q-learning, SARSA, and
Deep Q-Networks are examples. Policy-based methods directly optimize a parameterized policy
$pi_theta(a | s)$, which is useful for continuous, stochastic, or very large action spaces but can
have high-variance gradient estimates. Actor--critic methods combine a policy-producing actor with a
value-estimating critic, using the critic's values or advantages to improve the actor. Common
actor--critic algorithms include A2C, A3C, DDPG, SAC, and PPO.

RL must balance exploration, trying uncertain actions to gain information, against exploitation,
choosing actions already estimated to be effective. It also distinguishes on-policy learning, which
updates from data generated by the current policy, from off-policy learning, which can reuse data
generated by another or an older policy.

=== Proximal Policy Optimization <background-ppo>

Proximal Policy Optimization (PPO) is an on-policy actor--critic method that limits the size of a
policy update. For an action sampled from an old policy, it considers the probability ratio

$
  r_t(theta) = frac(pi_theta(a_t | s_t), pi_("old")(a_t | s_t))
$

and clips it to a range around one. This favors changes that improve the estimated advantage while
discouraging an update from making the action much more or much less likely in a single step. The
constraint generally improves stability relative to unconstrained policy-gradient updates.

=== Reinforcement learning for language models <background-rl-for-llms>

An autoregressive language model can be viewed as a policy:

$
  pi_theta(y_t | x, y_(<t)),
$

where $x$ is a prompt, $y_(<t)$ is the generated prefix, and the next token $y_t$ is an action. A
full response is a rollout. A reward $r(x, y)$ can represent response quality, correctness, or a
preference for a generated response $y$.

Rewards may come from human preferences, a learned reward model, feedback from another model, or
automatic verification such as checking a mathematical answer or running program tests. In a
classical reinforcement-learning-from-human-feedback (RLHF) pipeline, a pretrained language model is
supervised fine-tuned, human preference data trains a reward model, and RL then optimizes the
language model against that reward.

PPO-based language-model training commonly adds a Kullback--Leibler (KL) penalty relative to a
reference policy:

$
  R_("total") = R_("task") - beta D_("KL")(pi_theta || pi_("ref")).
$

The reference policy anchors optimization near the original model behavior. It can reduce extreme
distribution shifts, but it does not ensure that the reward captures the intended behavior.

=== Reasoning-oriented optimization

For reasoning tasks, training can sample several rollouts for one prompt, evaluate them, and
increase the probability of relatively successful trajectories. Group-based approaches such as GRPO
use rewards from a group of responses to form relative advantages; this can avoid a separately
learned value function for each response. Multiple rollouts are most informative when they contain
both successful and unsuccessful solutions, because they provide a comparison signal.

Compared with supervised fine-tuning (SFT), which imitates target responses, RL optimizes evaluated
model-generated behavior. This lets a model explore multiple valid solution paths when an evaluator
can judge their outcomes, but it makes rollout generation and evaluation central costs.

=== Limitations and practical concerns

Long responses may receive only a terminal reward, making credit assignment across many generated
tokens difficult. Sampling must be diverse enough to discover improved trajectories without wasting
computation on predominantly poor ones. Rollout generation, reward-model inference, and human
evaluation can be expensive. Most importantly, a model can exploit a proxy reward rather than
achieve the intended objective---for example, producing unnecessarily long responses if a reward
model mistakenly favors length. This reward-hacking risk makes reward design and evaluation crucial
in RL for language models.
